# Generated by Django 5.2.10 on 2026-01-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Web Development', 'Web Development'), ('Mobile Apps', 'Mobile Apps'), ('UI/UX', 'UI/UX'), ('Research', 'Research'), ('Academic', 'Academic')], max_length=40)),
                ('tech', models.JSONField(blank=True, default=list)),
                ('url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
